# Generated by Django 6.1.1 on 2026-09-07 01:55

import chores.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default=chores.models.default_timezone, help_text='IANA timezone name. Due times are computed and displayed in it.', max_length=64, validators=[chores.models.validate_timezone])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='household_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Set of role names from ROLE_CHOICES. May be empty.')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='chores.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'household'), name='unique_membership_per_user_and_household')],
            },
        ),
    ]
