# Generated by Django 6.1.1 on 2026-09-07 02:15

import chores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_household_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(max_length=200, validators=[chores.models.validate_not_blank]),
        ),
    ]
