# Generated by Django 6.1.1 on 2026-09-07 11:50

import chores.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_household_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[chores.models.validate_not_blank])),
                ('estimated_minutes', models.PositiveIntegerField(help_text='Rough duration in minutes. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.PositiveSmallIntegerField(help_text='How demanding the chore is, from 1 (easy) to 5 (hard).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('assignment_mode', models.CharField(choices=[('rotate', 'Rotate between members'), ('assign', 'Always the same person'), ('claim', 'Anyone can claim it')], help_text='How the chore finds an owner each time it comes round.', max_length=16)),
                ('start_date', models.DateField(help_text="First date the chore is due, in the household's own calendar.")),
                ('recurrence', models.CharField(choices=[('one_off', 'One-off'), ('interval', 'Every N days')], default='one_off', help_text='Whether the chore happens once or every interval_days days.', max_length=16)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text="Whole days between occurrences. Required for 'interval', empty otherwise.", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fixed_member', models.ForeignKey(blank=True, help_text="Required in 'assign' mode, and must be empty otherwise.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_chore_definitions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chore_definitions', to='chores.household')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chore_definition_name_not_blank'), models.UniqueConstraint(fields=('household', 'name'), name='unique_chore_definition_name_per_household'), models.CheckConstraint(condition=models.Q(('estimated_minutes__gt', 0)), name='chore_definition_estimated_minutes_positive'), models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='chore_definition_difficulty_in_range'), models.CheckConstraint(condition=models.Q(models.Q(('assignment_mode', 'assign'), _negated=True), ('fixed_member__isnull', False), _connector='OR'), name='chore_definition_assign_mode_names_a_fixed_member'), models.CheckConstraint(condition=models.Q(('assignment_mode', 'assign'), ('fixed_member__isnull', True), _connector='OR'), name='chore_definition_other_modes_have_no_fixed_member'), models.CheckConstraint(condition=models.Q(models.Q(('recurrence', 'interval'), _negated=True), ('interval_days__isnull', False), _connector='OR'), name='chore_definition_interval_recurrence_has_interval_days'), models.CheckConstraint(condition=models.Q(models.Q(('recurrence', 'one_off'), _negated=True), ('interval_days__isnull', True), _connector='OR'), name='chore_definition_one_off_recurrence_has_no_interval_days'), models.CheckConstraint(condition=models.Q(('interval_days__isnull', True), ('interval_days__gt', 0), _connector='OR'), name='chore_definition_interval_days_positive')],
            },
        ),
    ]
