# Generated by Django 6.1.1 on 2026-09-07 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_choredefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(help_text='When the chore is due, stored in UTC.')),
                ('estimated_minutes', models.PositiveIntegerField(help_text='Rough duration in minutes, frozen from the definition. At least 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.PositiveSmallIntegerField(help_text='How demanding the chore is, frozen from the definition, 1 (easy) to 5 (hard).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', help_text='Pending until it is done. Overdue is a separate flag, not a state.', max_length=16)),
                ('assignee', models.ForeignKey(blank=True, help_text="Who owes this. Empty until someone claims a 'claim' chore.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_occurrences', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(help_text='The chore this is an instance of. The household comes from it.', on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='chores.choredefinition')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('estimated_minutes__gt', 0)), name='chore_occurrence_estimated_minutes_positive'), models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='chore_occurrence_difficulty_in_range'), models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'done'])), name='chore_occurrence_state_in_choices'), models.UniqueConstraint(fields=('definition', 'due_at'), name='unique_occurrence_per_definition_and_due_at')],
            },
        ),
    ]
