# Generated by Django 6.1.1 on 2026-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_choreoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreoccurrence',
            name='overdue_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the chore first went late, stored in UTC. Empty until it does. Overdue is a flag, not a state: the occurrence stays pending and stays owed.', null=True),
        ),
    ]
